"""
djresource.mixins
==================

Mixins used to dynamically compose the views generated by `Resource`.

Each mixin does exactly one thing and respects the `super()` chain, so it
can be freely combined in `Resource.get_*_view()` without overriding the
behavior of the other mixins (see resource.py).

MIXIN ORDER IN THE BASES (important, don't change without understanding it):
For Create/Update, the order is:
    ResourceContextMixin, ResourceFormActionMixin, ResourceCreateMessageMixin,
    ResourceInlineFormsetMixin, ResourceSaveHooksMixin, *permissions, CreateView
The outermost "form_valid" (message) wraps the formset, which wraps the
actual save (hooks). Each mixin calls super() to delegate to the next
one; the order in the bases tuple IS the execution order (the first one
listed runs first).
"""
from django.contrib import messages
from django.core.exceptions import ValidationError as DjangoValidationError
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse


# ---------------------------------------------------------------------
# Common context (all generated views)
# ---------------------------------------------------------------------
class ResourceContextMixin:
    """
    Injects the resource, useful route names, and additional business
    context (via `Resource.get_extra_context()`) into the template
    context.
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        resource = self.resource
        context["resource"] = resource
        context["verbose_name"] = resource.verbose_name
        context["verbose_name_plural"] = resource.model._meta.verbose_name_plural
        context["url_list"] = resource.url_name("list")
        context["url_create"] = resource.url_name("create")
        context["url_detail"] = resource.url_name("detail")
        context["url_update"] = resource.url_name("update")
        context["url_delete"] = resource.url_name("delete")

        extra = resource.get_extra_context(self)
        if extra:
            context.update(extra)
        return context


class ResourceListContextMixin(ResourceContextMixin):
    """Adds the columns to display (list_display) to the list context."""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list_display"] = self.resource.list_display
        return context


class ResourceQuerysetMixin:
    """Builds the request-scoped queryset used by every generated view."""

    def get_queryset(self):
        return self.resource.get_queryset(getattr(self, "request", None))


class ResourceFormActionMixin:
    """
    Computes `form_action_url`, used by the form template to explicitly
    post to the create/update URL generated by the library — needed
    for the form to also work when it's injected (via
    `{% djresource_form %}`) into a page that isn't itself the
    create/update view.
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        resource = self.resource
        obj = getattr(self, "object", None)
        if obj is not None and obj.pk:
            lookup_value = resource.get_lookup_value(obj)
            context["form_action_url"] = reverse(resource.url_name("update"), args=[lookup_value])
        else:
            context["form_action_url"] = reverse(resource.url_name("create"))
        return context


class ResourceLookupMixin:
    """
    Retrieves the object via `Resource.lookup_field` ("pk" by default,
    but can be any unique field on the model: "slug", "name"...).
    """

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        resource = self.resource
        lookup_value = self.kwargs[resource.lookup_url_kwarg]
        return get_object_or_404(queryset, **{resource.lookup_field: lookup_value})


# ---------------------------------------------------------------------
# Search and sorting (ListView only)
# ---------------------------------------------------------------------
class ResourceSearchMixin:
    """
    Adds a simple text search on the fields declared in `search_fields`,
    via the GET parameter `?q=...`.
    """

    search_fields = []

    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get("q", "").strip()
        if query and self.search_fields:
            filters = Q()
            for field in self.search_fields:
                filters |= Q(**{f"{field}__icontains": query})
            qs = qs.filter(filters)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_query"] = self.request.GET.get("q", "")
        context["search_enabled"] = bool(self.search_fields)
        return context


class ResourceOrderingMixin:
    """
    Allows sorting the list via `?sort=field&dir=asc|desc`, restricted
    to fields declared in `ordering_fields`.
    """

    ordering_fields = []

    def get_queryset(self):
        qs = super().get_queryset()
        sort = self.request.GET.get("sort")
        direction = self.request.GET.get("dir", "asc")
        if sort and sort in self.ordering_fields:
            qs = qs.order_by(sort if direction == "asc" else f"-{sort}")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_sort"] = self.request.GET.get("sort", "")
        context["current_dir"] = self.request.GET.get("dir", "asc")
        return context


class ResourceFilterMixin:
    """
    Filters the list via `?field=value`, restricted to fields declared
    in the Resource's `list_filter` (typically booleans and fields with
    `choices`). Filters combine with each other and with the `?q=`
    search (logical AND). Validation is delegated to the Resource
    (`get_active_list_filters`), shared with `get_list_context()`.
    """

    def get_queryset(self):
        qs = super().get_queryset()
        params = self.request.GET if getattr(self, "request", None) else {}
        return self.resource.apply_list_filters(qs, params)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        params = self.request.GET if getattr(self, "request", None) else {}
        context["filters_enabled"] = bool(self.resource.list_filter)
        context["list_filters"] = self.resource.get_list_filter_options(
            params, getattr(self, "request", None)
        )
        return context


# ---------------------------------------------------------------------
# Saving: business logic hooks (before_save/after_save/clean)
# ---------------------------------------------------------------------
class ResourceSaveHooksMixin:
    """
    Replaces the default form_valid() of Create/UpdateView to call the
    Resource's business logic hooks (`clean`, `before_save`,
    `after_save`) around the save.

    Uses `form.save(commit=False)` to be able to intervene before the
    database write, then explicitly calls `save_m2m()` (required by
    Django as soon as `commit=False` is used on a ModelForm with
    ManyToMany fields — without this, M2M relations would never be
    saved).
    """

    def form_valid(self, form):
        resource = self.resource
        is_new = form.instance.pk is None
        instance = form.save(commit=False)

        try:
            resource.clean(instance, self.request)
        except DjangoValidationError as exc:
            form.add_error(None, exc)
            return self.form_invalid(form)

        resource.before_save(instance, self.request, is_new)
        instance.save()
        if hasattr(form, "save_m2m"):
            form.save_m2m()
        resource.after_save(instance, self.request, is_new)

        self.object = instance
        return HttpResponseRedirect(self.get_success_url())


class ResourceDeleteHooksMixin:
    """
    Calls `Resource.before_delete()` / `after_delete()` around the
    deletion. `before_delete` can raise `ValidationError` to prevent the
    deletion (error message shown, object kept).
    """

    def form_valid(self, form):
        resource = self.resource
        instance = self.object
        try:
            resource.before_delete(instance, self.request)
        except DjangoValidationError as exc:
            messages.error(self.request, str(exc))
            return HttpResponseRedirect(self.request.path)

        response = super().form_valid(form)  # performs the actual deletion (Django)
        resource.after_delete(instance, self.request)
        return response


# ---------------------------------------------------------------------
# Inline formsets (editing related objects within the same form)
# ---------------------------------------------------------------------
class ResourceInlineFormsetMixin:
    """
    Manages formsets declared via `Resource.inlines`: instantiation
    (GET), validation (POST), and saving AFTER the parent object is
    saved (necessary: the related rows need the parent's `pk`, which
    only exists once the parent has been saved).

    Must be placed BEFORE `ResourceSaveHooksMixin` in the bases (so its
    `form_valid` runs first, and its `super().form_valid()` delegates
    saving the parent to the next mixin).
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "inline_formsets" not in context:
            context["inline_formsets"] = self._build_formsets(
                instance=getattr(self, "object", None), data=None, files=None
            )
        return context

    def _build_formsets(self, instance, data, files):
        formsets = []
        for inline in self.resource.inlines:
            formset_class = inline.get_formset_class(self.resource.model)
            if data is not None:
                formsets.append(formset_class(data, files, instance=instance))
            else:
                formsets.append(formset_class(instance=instance))
        return formsets

    def form_valid(self, form):
        if not self.resource.inlines:
            return super().form_valid(form)

        formsets = self._build_formsets(
            instance=form.instance, data=self.request.POST, files=self.request.FILES
        )
        if not all(fs.is_valid() for fs in formsets):
            return self.render_to_response(
                self.get_context_data(form=form, inline_formsets=formsets)
            )

        # Save the parent first (delegates to ResourceSaveHooksMixin,
        # which calls the before/after hooks): self.object has a pk after this.
        response = super().form_valid(form)

        for formset in formsets:
            formset.instance = self.object
            formset.save()

        return response


# ---------------------------------------------------------------------
# Success messages (Create / Update / Delete)
# ---------------------------------------------------------------------
class ResourceCreateMessageMixin:
    """
    Adds a success message after creation. Only adds it if the response
    is a redirect: if an inline formset is invalid, form_valid() may
    just re-render the form (200) instead of redirecting — in that case,
    no false success message.
    """

    def form_valid(self, form):
        response = super().form_valid(form)
        if isinstance(response, HttpResponseRedirect):
            messages.success(
                self.request,
                self.resource.success_message_create % {"name": self.resource.verbose_name},
            )
        return response


class ResourceUpdateMessageMixin:
    """Adds a success message after update (same guard as above)."""

    def form_valid(self, form):
        response = super().form_valid(form)
        if isinstance(response, HttpResponseRedirect):
            messages.success(
                self.request,
                self.resource.success_message_update % {"name": self.resource.verbose_name},
            )
        return response


class ResourceDeleteMessageMixin:
    """Adds a success message after deletion."""

    def form_valid(self, form):
        object_repr = str(self.object)
        response = super().form_valid(form)
        messages.success(
            self.request,
            self.resource.success_message_delete % {"name": object_repr},
        )
        return response
